version: '2'
services:
  kafka:
    image: spotify/kafka
    ports:
     - "2181:2181"
     - "9092:9092"
    environment:
     - "ADVERTISED_HOST=192.168.99.100"
     - "ADVERTISED_PORT=9092"
  synopticservice:
    image: vballada/synoptic-service
    restart: always
    ports:
     - "8090:8090"
    environment:
     - "SPRING_PROFILES_ACTIVE=docker"
    links:
     - kafka
    depends_on:
     - kafka
  synopticclient:
    image: vballada/synoptic-client
    restart: always
    ports:
     - "8080:8080"
    environment:
     - "SPRING_PROFILES_ACTIVE=docker"
    links:
     - kafka
    depends_on:
     - kafka
  